### ISSUE TITLE
String Interpolation

### ISSUE THREAD

**Issue by swsmith50** [learn-co-curriculum/getting-user-data-command-line-codealong#2]
In the previous lesson, "String Interpolation" it's suggested that   + variable_name +   is a method for interpolation we should avoid and instead we should use #{variable_name}. Yet, here in this lesson you revert to + variable_name + in the first coding example. I understand that it's a valid method and works, but shouldn't the lessons be consistent?

**Comment by aviflombaum** [comment]
Ya thats interesting, for now I guess knowing the two styles is fine - closing this.
